// Modal elements
const applyBtn = document.getElementById('applyBtn');
const applicationModal = document.getElementById('applicationModal');
const successModal = document.getElementById('successModal');
const closeBtn = document.getElementById('closeBtn');
const creditForm = document.getElementById('creditForm');
const pageBody = document.body;
const notify = window.showNotice || (() => {});

// Form validation setup
// eslint-disable-next-line no-unused-vars
const form = creditForm;

function setModalState(modal, isOpen) {
  if (!modal) {
    return;
  }

  modal.classList.toggle('show', isOpen);
  modal.setAttribute('aria-hidden', String(!isOpen));
  pageBody.style.overflow = isOpen ? 'hidden' : '';

  if (isOpen) {
    const focusTarget = modal.querySelector('input, select, textarea, button');
    if (focusTarget) {
      focusTarget.focus();
    }
  }
}

// Open application form modal
applyBtn.addEventListener('click', () => {
  setModalState(applicationModal, true);
});

// Close application form modal
closeBtn.addEventListener('click', () => {
  setModalState(applicationModal, false);
});

// Close modal when clicking outside of it
window.addEventListener('click', (e) => {
  if (e.target === applicationModal) {
    setModalState(applicationModal, false);
  }
  if (e.target === successModal) {
    setModalState(successModal, false);
  }
});

document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') {
    setModalState(applicationModal, false);
    setModalState(successModal, false);
  }
});

// Form submission
creditForm.addEventListener('submit', async (e) => {
  e.preventDefault();

  // Get form data
  const formData = new FormData(creditForm);
  const data = Object.fromEntries(formData);

  // Validate form
  if (!validateForm(data)) {
    notify('Please fill all required fields correctly', 'error');
    return;
  }

  try {
    const response = await window.apiFetch('/credit-applications', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        fullName: data.fullName,
        email: data.email,
        phone: data.phone,
        dob: data.dob,
        panNumber: data.panNumber,
        address: data.address,
        city: data.city,
        state: data.state,
        pincode: data.pincode,
        residenceType: data.residenceType,
        employmentType: data.employmentType,
        monthlyIncome: data.monthlyIncome,
        company: data.company,
        creditAmount: data.creditAmount,
        repaymentPeriod: data.repaymentPeriod
      })
    });

    showSuccessModal(response.referenceId);
  } catch (error) {
    notify(error.message, 'error');
    return;
  }

  // Reset form
  creditForm.reset();
});

// Form validation function
function validateForm(data) {
  // Check email format
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(data.email)) {
    notify('Please enter a valid email address', 'error');
    return false;
  }

  // Check phone format
  if (data.phone.length !== 10 || !/^\d+$/.test(data.phone)) {
    notify('Please enter a valid 10-digit phone number', 'error');
    return false;
  }

  // Check PAN format
  const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;
  if (!panRegex.test(data.panNumber)) {
    notify('Please enter a valid PAN number (e.g., ABCDE1234F)', 'error');
    return false;
  }

  // Check age (must be 18+)
  const dob = new Date(data.dob);
  const age = new Date().getFullYear() - dob.getFullYear();
  if (age < 18) {
    notify('You must be at least 18 years old to apply', 'error');
    return false;
  }

  // Check pincode format
  if (data.pincode.length !== 6 || !/^\d+$/.test(data.pincode)) {
    notify('Please enter a valid 6-digit pincode', 'error');
    return false;
  }

  // Check monthly income
  if (parseFloat(data.monthlyIncome) <= 0) {
    notify('Please enter a valid monthly income', 'error');
    return false;
  }

  // Check credit amount
  if (parseFloat(data.creditAmount) <= 0 || parseFloat(data.creditAmount) > 1000000) {
    notify('Credit amount should be between ₹0 and ₹10,00,000', 'error');
    return false;
  }

  // Check terms agreement
  if (!document.getElementById('agreeTerms').checked) {
    notify('Please agree to terms and conditions', 'error');
    return false;
  }

  return true;
}

// Show success modal
function showSuccessModal(referenceId) {
  document.getElementById('referenceId').textContent = referenceId;

  // Close application modal and show success modal
  setModalState(applicationModal, false);
  setModalState(successModal, true);
}

// Generate reference ID
// Reference IDs are generated by the backend.

// Real-time validation for email
const emailInput = document.getElementById('email');
if (emailInput) {
  emailInput.addEventListener('blur', () => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (emailInput.value && !emailRegex.test(emailInput.value)) {
      emailInput.style.borderColor = '#ff6b6b';
    } else {
      emailInput.style.borderColor = '#e0e0e0';
    }
  });
}

// Real-time validation for phone
const phoneInput = document.getElementById('phone');
if (phoneInput) {
  phoneInput.addEventListener('input', () => {
    phoneInput.value = phoneInput.value.replace(/\D/g, '').slice(0, 10);
  });

  phoneInput.addEventListener('blur', () => {
    if (phoneInput.value && phoneInput.value.length !== 10) {
      phoneInput.style.borderColor = '#ff6b6b';
    } else {
      phoneInput.style.borderColor = '#e0e0e0';
    }
  });
}

// Real-time validation for pincode
const pincodeInput = document.getElementById('pincode');
if (pincodeInput) {
  pincodeInput.addEventListener('input', () => {
    pincodeInput.value = pincodeInput.value.replace(/\D/g, '').slice(0, 6);
  });

  pincodeInput.addEventListener('blur', () => {
    if (pincodeInput.value && pincodeInput.value.length !== 6) {
      pincodeInput.style.borderColor = '#ff6b6b';
    } else {
      pincodeInput.style.borderColor = '#e0e0e0';
    }
  });
}

// Real-time validation for PAN
const panInput = document.getElementById('panNumber');
if (panInput) {
  panInput.addEventListener('input', () => {
    panInput.value = panInput.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 10);
  });

  panInput.addEventListener('blur', () => {
    const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/;
    if (panInput.value && !panRegex.test(panInput.value)) {
      panInput.style.borderColor = '#ff6b6b';
    } else {
      panInput.style.borderColor = '#e0e0e0';
    }
  });
}

// Calculate EMI on repayment period change
const creditAmountInput = document.getElementById('creditAmount');
const repaymentPeriod = document.getElementById('repaymentPeriod');

if (repaymentPeriod) {
  repaymentPeriod.addEventListener('change', () => {
    const amount = parseFloat(creditAmountInput.value) || 0;
    const period = repaymentPeriod.value;

    if (amount > 0 && period) {
      const rates = {
        '30': 0,
        '90': 0.08,
        '180': 0.10,
        '360': 0.12
      };

      const annualRate = rates[period];
      const months = period / 30;
      const monthlyRate = annualRate / 12;

      // Simple EMI calculation
      let emi = 0;
      if (monthlyRate === 0) {
        emi = amount / months;
      } else {
        emi = (amount * monthlyRate * Math.pow(1 + monthlyRate, months)) /
              (Math.pow(1 + monthlyRate, months) - 1);
      }

      notify(`Estimated EMI: ₹${emi.toFixed(2)} per month`, 'info', { timeout: 3000 });
    }
  });
}
